name: Garbage Video Collector

on: 
  workflow_dispatch:
  schedule:
    # 08:00 UTC equivale a las 05:00 AM en Argentina (UTC-3)
    - cron: '0 8 * * *'

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Run GhostBuster (Upcoming)
      env:
        YOUTUBE_APIKEY: ${{ secrets.YOUTUBE_APIKEY }}
        FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
        MONGODB_CONNECTIONSTRING: ${{ secrets.MONGODB_CONNECTIONSTRING }}
        MONGODB_DATABASENAME: ${{ secrets.MONGODB_DATABASENAME }}
      # ¡Fíjate en el argumento "upcoming" al final!
      run: dotnet run --project ./ZappingStreamingLiveChecker/ZappingStreamingLiveChecker/ZappingStreamingLiveChecker.csproj -- --purgarDescartados
