name: Ghost Buster Cron Job

# Cuándo se ejecuta
on:
  workflow_dispatch: # Te permite correrlo a mano desde la web de GitHub
  schedule:
    - cron: '13 * * * *' # Corre todas las horas a los 13 minutos

# Qué es lo que hace
jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Run GhostBuster (Upcoming)
      env:
        YOUTUBE_APIKEY: ${{ secrets.YOUTUBE_APIKEY }}
        FIREBASE_SECRET: ${{ secrets.FIREBASE_SECRET }}
      # ¡Fíjate en el argumento "upcoming" al final!
      run: dotnet run --project ./ZappingStreamingLiveChecker/ZappingStreamingLiveChecker/ZappingStreamingLiveChecker.csproj -- vivos
