name: Incoming Videos

on: # Cada 21 minutos
  workflow_dispatch:

jobs:
  build-and-run:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.0.x'
    - name: Run Incoming Videos
      env:
         YouTube__ApiKey: ${{ secrets.YOUTUBE_APIKEY }}
         Firebase__Secret: ${{ secrets.FIREBASE_SECRET }}
         MongoDB__ConnectionString: ${{ secrets.MONGODB_CONNECTIONSTRING }}
         MongoDB__DatabaseName: ${{ secrets.MONGODB_DATABASENAME }}
      # ¡Fíjate en el argumento "upcoming" al final!
      run: dotnet run --project ./ZappingStreamingIncomingVideos/ZappingStreamingIncomingVideos/ZappingStreamingIncomingVideos.csproj 
