name: Ejecutar Zapping Streaming DB Service

on:
 # schedule:
    # Esto corre al minuto 0 de cada hora (ej: 1:00, 2:00, 3:00...)
    # - cron: '0 * * * *'
    # - cron: '04,13,36,53 * * * *'
  # Esto te permite ejecutar el script a mano desde la pestaña "Actions" en GitHub para probarlo.
  workflow_dispatch: 

jobs:
  run-service:
    runs-on: ubuntu-latest

    steps:
    - name: Descargar el repositorio
      uses: actions/checkout@v4

    - name: Configurar .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x' 

    - name: Restaurar dependencias
      working-directory: ./ZappingStreamingChannelsResync/ZappingStreamingChannelsResync
      run: dotnet restore

    - name: Compilar
      working-directory: ./ZappingStreamingChannelsResync/ZappingStreamingChannelsResync
      run: dotnet build --no-restore

    - name: Ejecutar el servicio
      working-directory: ./ZappingStreamingChannelsResync/ZappingStreamingChannelsResync
      env:
         YouTube__ApiKey: ${{ secrets.YOUTUBE_APIKEY }}
         Firebase__Secret: ${{ secrets.FIREBASE_SECRET }}
      run: dotnet run --no-build
